**Pandas**

pandas is designed for data manipulation and analysis especially when dealing with structured data like csv files or sql tables.
There are two types:
1. pandas series
2.pandas dataframe

In [ ]:
#pandas series is like a column in a table.It is a 1-d array holding data of any type.
#importing libraries
import pandas as pd
import numpy as np

In [ ]:
#string
country=['India','U.S.A','England','Russia','Nepal']
print(country)
pd.Series(country)#pd.series()-->used to convert any dataype into pandas series.

['India', 'U.S.A', 'England', 'Russia', 'Nepal']

0      India
1      U.S.A
2    England
3     Russia
4      Nepal
dtype: object

In [ ]:
#integers
marks=[78,89,67,98,65]
print(pd.Series(marks))
#custom index
subjects=['Maths','English','Science','Python','Java']
pd.Series(marks,index=subjects)#index parameter is used to give our own index or custom index
#setting name
marks=pd.Series(marks,index=subjects,name="sam marks")#name is used togive name for pandas series table
marks

0    78
1    89
2    67
3    98
4    65
dtype: int64

Maths      78
English    89
Science    67
Python     98
Java       65
Name: sam marks, dtype: int64

**Series from dictionary**

In [ ]:
marks={'maths':78,
       'python':87,
       'java':28,
       'english':80
       }#key-value pari
marks_series=pd.Series(marks,name='sidd marks')#key --> index, value --> value
marks_series

maths      78
python     87
java       28
english    80
Name: sidd marks, dtype: int64

**Series Attributes(properties)**

In [ ]:
#size:Returns the number of elements in the series
print(marks_series.size)
#dtype:returns datatype of the value in series
print(marks_series.dtype)
#name:returns the name of the series
print(marks_series.name)
#is_unique: returns true if every value in series is unique else false.
print(marks_series.is_unique)
#index
print(marks_series.index)
#values
print(marks_series.values)
#type
type(marks_series.values)

4
int64
sidd marks
True
Index(['maths', 'python', 'java', 'english'], dtype='object')
[78 87 28 80]

numpy.ndarray

In [ ]:
data_set=pd.read_csv('/content/subs (1).csv')#csv files
data_set
#pd.read_csv--> it automatically converts  everthing into dataframe.

     Subscribers gained
0                    48
1                    57
2                    40
3                    43
4                    44
..                  ...
360                 231
361                 226
362                 155
363                 144
364                 172

[365 rows x 1 columns]

In [ ]:
type(data_set)

pandas.core.frame.DataFrame

In [ ]:
data_set.head()#gives first five values in dataset

   Subscribers gained
0                  48
1                  57
2                  40
3                  43
4                  44

In [ ]:
data_set.tail()#gives last five values in dataset

     Subscribers gained
360                 231
361                 226
362                 155
363                 144
364                 172

In [ ]:
data=pd.read_csv("/content/bollywood.csv")
data

                                     movie              lead
0                 Uri: The Surgical Strike     Vicky Kaushal
1                            Battalion 609       Vicky Ahuja
2     The Accidental Prime Minister (film)       Anupam Kher
3                          Why Cheat India     Emraan Hashmi
4                          Evening Shadows  Mona Ambegaonkar
...                                    ...               ...
1495                Hum Tumhare Hain Sanam    Shah Rukh Khan
1496                   Aankhen (2002 film)  Amitabh Bachchan
1497                       Saathiya (film)      Vivek Oberoi
1498                        Company (film)        Ajay Devgn
1499                  Awara Paagal Deewana      Akshay Kumar

[1500 rows x 2 columns]

In [ ]:
data.head()

                                  movie              lead
0              Uri: The Surgical Strike     Vicky Kaushal
1                         Battalion 609       Vicky Ahuja
2  The Accidental Prime Minister (film)       Anupam Kher
3                       Why Cheat India     Emraan Hashmi
4                       Evening Shadows  Mona Ambegaonkar

In [ ]:
data.tail()

                       movie              lead
1495  Hum Tumhare Hain Sanam    Shah Rukh Khan
1496     Aankhen (2002 film)  Amitabh Bachchan
1497         Saathiya (film)      Vivek Oberoi
1498          Company (film)        Ajay Devgn
1499    Awara Paagal Deewana      Akshay Kumar

In [ ]:
data.sample(5)#gives random value

                                     movie             lead
26    Albert Pinto Ko Gussa Kyun Aata Hai?       Manav Kaul
771                         Shaitan (film)   Kalki Koechlin
777                     Delhi Belly (film)       Imran Khan
353                           Wajah Tum Ho    Sharman Joshi
1380                          Paisa Vasool  Manisha Koirala

In [ ]:
#value_counts():Returns the counts of unique values.
data.value_counts()

movie                     lead
Andaaz                    Akshay Kumar       2
Tanu Weds Manu: Returns   Kangana Ranaut     2
Gabbar Is Back            Akshay Kumar       2
Noor (film)               Sunny Leone        1
No Smoking (2007 film)    John Abraham       1
                                            ..
Genius (2018 Hindi film)  Utkarsh Sharma     1
Gayab                     Tusshar Kapoor     1
Gauri: The Unborn         Mohan Azaad        1
Gattu                     Naresh Sharma      1
Global Baba               Pankaj Tripathi    1
Name: count, Length: 1497, dtype: int64

In [ ]:
data.sort_index()

                                     movie              lead
0                 Uri: The Surgical Strike     Vicky Kaushal
1                            Battalion 609       Vicky Ahuja
2     The Accidental Prime Minister (film)       Anupam Kher
3                          Why Cheat India     Emraan Hashmi
4                          Evening Shadows  Mona Ambegaonkar
...                                    ...               ...
1495                Hum Tumhare Hain Sanam    Shah Rukh Khan
1496                   Aankhen (2002 film)  Amitabh Bachchan
1497                       Saathiya (film)      Vivek Oberoi
1498                        Company (film)        Ajay Devgn
1499                  Awara Paagal Deewana      Akshay Kumar

[1500 rows x 2 columns]

In [ ]:
print(data.mode())

                     movie          lead
0                   Andaaz  Akshay Kumar
1           Gabbar Is Back           NaN
2  Tanu Weds Manu: Returns           NaN

**IMPORT DATASET**

In [ ]:
data=pd.read_csv("/content/1000000.csv")
data

       ID   Name  Age   Department    Salary         City
0       1    Eva   30  Engineering   63479.0  Los Angeles
1       2  Alice   24           HR   77616.0      Chicago
2       3  David   37           HR   55139.0      Houston
3       4  David   23      Finance  112594.0  Los Angeles
4       5  David   57      Finance   94352.0      Houston
..    ...    ...  ...          ...       ...          ...
995   996    Eva   31  Engineering  107931.0      Houston
996   997  David   56  Engineering   74962.0     New York
997   998    Bob   38        Sales   64173.0  Los Angeles
998   999    Bob   31        Sales  101536.0      Houston
999  1000  David   54  Engineering   65371.0  Los Angeles

[1000 rows x 6 columns]

**Inspecting data**

In [ ]:
data.head(6)

   ID   Name  Age   Department    Salary         City
0   1    Eva   30  Engineering   63479.0  Los Angeles
1   2  Alice   24           HR   77616.0      Chicago
2   3  David   37           HR   55139.0      Houston
3   4  David   23      Finance  112594.0  Los Angeles
4   5  David   57      Finance   94352.0      Houston
5   6    Bob   50           HR   94535.0      Chicago

In [ ]:
data.tail()

       ID   Name  Age   Department    Salary         City
995   996    Eva   31  Engineering  107931.0      Houston
996   997  David   56  Engineering   74962.0     New York
997   998    Bob   38        Sales   64173.0  Los Angeles
998   999    Bob   31        Sales  101536.0      Houston
999  1000  David   54  Engineering   65371.0  Los Angeles

In [ ]:
data.sample(3)

      ID   Name  Age   Department   Salary         City
492  493  Alice   34  Engineering  45602.0     New York
46    47  Alice   48        Sales  30075.0     New York
383  384    Bob   51        Sales  51300.0  Los Angeles

In [ ]:
data.shape#rows and columns

(1000, 6)

In [ ]:
data.info()#information of dataset

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   ID          1000 non-null   int64
 1   Name        998 non-null    object
 2   Age         1000 non-null   int64
 3   Department  995 non-null    object
 4   Salary      994 non-null    float64
 5   City        997 non-null    object
dtypes: float64(1), int64(2), object(3)
memory usage: 47.0+ KB

In [ ]:
data.describe()

                ID          Age         Salary
count  1000.000000  1000.000000     994.000000
mean    500.500000    39.743000   74303.895372
std     288.819436    11.517013   26723.333316
min       1.000000    20.000000       0.000000
25%     250.750000    30.000000   51348.000000
50%     500.500000    40.000000   73112.500000
75%     750.250000    49.000000   98715.500000
max    1000.000000    59.000000  119974.000000

In [ ]:
data.dtypes #print datatype of each column

ID              int64
Name           object
Age             int64
Department     object
Salary        float64
City           object
dtype: object

In [ ]:
data.columns

Index(['ID', 'Name', 'Age', 'Department', 'Salary', 'City'], dtype='object')

In [ ]:
data.index #range of index

RangeIndex(start=0, stop=1000, step=1)

**SELECTING DATA BY INDEX**

In [ ]:
data['Department']#select single column

0      Engineering
1               HR
2               HR
3          Finance
4          Finance
          ...
995    Engineering
996    Engineering
997          Sales
998          Sales
999    Engineering
Name: Department, Length: 1000, dtype: object

In [ ]:
data[['Salary','Name','Department']]#slect multiple columns

       Salary   Name   Department
0     63479.0    Eva  Engineering
1     77616.0  Alice           HR
2     55139.0  David           HR
3    112594.0  David      Finance
4     94352.0  David      Finance
..        ...    ...          ...
995  107931.0    Eva  Engineering
996   74962.0  David  Engineering
997   64173.0    Bob        Sales
998  101536.0    Bob        Sales
999   65371.0  David  Engineering

[1000 rows x 3 columns]

In [ ]:
data.iloc[0]#it will select row value

ID                      1
Name                  Eva
Age                    30
Department    Engineering
Salary            63479.0
City          Los Angeles
Name: 0, dtype: object

In [ ]:
data.iloc[1,5]#specific column value by index

'Chicago'

In [ ]:
data.loc[1,'City']# specific column value by column name

'Chicago'

In [ ]:
data[data['Age']>30]#selecting values by specific condition

       ID     Name  Age   Department    Salary         City
2       3    David   37           HR   55139.0      Houston
4       5    David   57      Finance   94352.0      Houston
5       6      Bob   50           HR   94535.0      Chicago
6       7    David   43      Finance   93175.0      Houston
7       8  Charlie   49           HR   75856.0     New York
..    ...      ...  ...          ...       ...          ...
995   996      Eva   31  Engineering  107931.0      Houston
996   997    David   56  Engineering   74962.0     New York
997   998      Bob   38        Sales   64173.0  Los Angeles
998   999      Bob   31        Sales  101536.0      Houston
999  1000    David   54  Engineering   65371.0  Los Angeles

[732 rows x 6 columns]

In [ ]:
data.iloc[5:9,2:5]

   Age Department   Salary
5   50         HR  94535.0
6   43    Finance  93175.0
7   49         HR  75856.0
8   58         HR  46386.0

In [ ]:
data1=data.set_index('ID')#slect columns as new index

**Cleaning dataset**

In [ ]:
#if we have zeros value or null value in our dataset.there is no use with that values.so, we have to remove those values or we can replace with mean,median or mode valye.
data.isnull().sum()#checks for null(empty) values,sum()--total ount null values

ID            0
Name          2
Age           0
Department    5
Salary        6
City          3
dtype: int64

In [ ]:
data.notnull().sum()#it will check for non-null values(empty values)

ID            1000
Name           998
Age           1000
Department     995
Salary         994
City           997
dtype: int64

In [ ]:
data.fillna('sam')#replace null-values with

       ID   Name  Age   Department    Salary         City
0       1    Eva   30  Engineering   63479.0  Los Angeles
1       2  Alice   24           HR   77616.0      Chicago
2       3  David   37           HR   55139.0      Houston
3       4  David   23      Finance  112594.0  Los Angeles
4       5  David   57      Finance   94352.0      Houston
..    ...    ...  ...          ...       ...          ...
995   996    Eva   31  Engineering  107931.0      Houston
996   997  David   56  Engineering   74962.0     New York
997   998    Bob   38        Sales   64173.0  Los Angeles
998   999    Bob   31        Sales  101536.0      Houston
999  1000  David   54  Engineering   65371.0  Los Angeles

[1000 rows x 6 columns]

In [ ]:
data1=data.dropna()#remove the null-values

In [ ]:
data1.isnull().sum()

ID            0
Name          0
Age           0
Department    0
Salary        0
City          0
dtype: int64

In [ ]:
data

       ID   Name  Age   Department    Salary         City
0       1    Eva   30  Engineering   63479.0  Los Angeles
1       2  Alice   24           HR   77616.0      Chicago
2       3  David   37           HR   55139.0      Houston
3       4  David   23      Finance  112594.0  Los Angeles
4       5  David   57      Finance   94352.0      Houston
..    ...    ...  ...          ...       ...          ...
995   996    Eva   31  Engineering  107931.0      Houston
996   997  David   56  Engineering   74962.0     New York
997   998    Bob   38        Sales   64173.0  Los Angeles
998   999    Bob   31        Sales  101536.0      Houston
999  1000  David   54  Engineering   65371.0  Los Angeles

[1000 rows x 6 columns]

In [ ]:
data.replace('David','sidd')#replace old value with value
data.replace('Bob','sam')

       ID   Name  Age   Department    Salary         City
0       1    Eva   30  Engineering   63479.0  Los Angeles
1       2  Alice   24           HR   77616.0      Chicago
2       3  David   37           HR   55139.0      Houston
3       4  David   23      Finance  112594.0  Los Angeles
4       5  David   57      Finance   94352.0      Houston
..    ...    ...  ...          ...       ...          ...
995   996    Eva   31  Engineering  107931.0      Houston
996   997  David   56  Engineering   74962.0     New York
997   998    sam   38        Sales   64173.0  Los Angeles
998   999    sam   31        Sales  101536.0      Houston
999  1000  David   54  Engineering   65371.0  Los Angeles

[1000 rows x 6 columns]

In [ ]:
data.rename(columns={'Name':'Full Name','Salary':'pay'})#It will rename the column name

       ID Full Name  Age   Department       pay         City
0       1       Eva   30  Engineering   63479.0  Los Angeles
1       2     Alice   24           HR   77616.0      Chicago
2       3     David   37           HR   55139.0      Houston
3       4     David   23      Finance  112594.0  Los Angeles
4       5     David   57      Finance   94352.0      Houston
..    ...       ...  ...          ...       ...          ...
995   996       Eva   31  Engineering  107931.0      Houston
996   997     David   56  Engineering   74962.0     New York
997   998       Bob   38        Sales   64173.0  Los Angeles
998   999       Bob   31        Sales  101536.0      Houston
999  1000     David   54  Engineering   65371.0  Los Angeles

[1000 rows x 6 columns]

In [ ]:
data.drop_duplicates()# drop only duplicate rows(same rows)

       ID   Name  Age   Department    Salary         City
0       1    Eva   30  Engineering   63479.0  Los Angeles
1       2  Alice   24           HR   77616.0      Chicago
2       3  David   37           HR   55139.0      Houston
3       4  David   23      Finance  112594.0  Los Angeles
4       5  David   57      Finance   94352.0      Houston
..    ...    ...  ...          ...       ...          ...
995   996    Eva   31  Engineering  107931.0      Houston
996   997  David   56  Engineering   74962.0     New York
997   998    Bob   38        Sales   64173.0  Los Angeles
998   999    Bob   31        Sales  101536.0      Houston
999  1000  David   54  Engineering   65371.0  Los Angeles

[1000 rows x 6 columns]

In [ ]:
data.sort_values('Salary')#sort the values by ascending order.
data.sort_values('Salary',ascending=False)#sort the values by descending order

      ID     Name  Age   Department    Salary         City
164  165      Bob   44  Engineering  119974.0  Los Angeles
611  612  Charlie   41  Engineering  119886.0     New York
973  974  Charlie   36        Sales  119874.0      Chicago
624  625      Bob   56  Engineering  119836.0      Chicago
573  574  Charlie   44        Sales  119830.0      Houston
..   ...      ...  ...          ...       ...          ...
19    20      Eva   50  Engineering       NaN     New York
26    27    Alice   59      Finance       NaN      Houston
292  293    Alice   54  Engineering       NaN      Houston
304  305  Charlie   37  Engineering       NaN  Los Angeles
333  334  Charlie   46  Engineering       NaN  Los Angeles

[1000 rows x 6 columns]

In [ ]:
data.query('Age>20 and Salary>50000 and Department =="HR"')#use multiple conditions like query in SQL

      ID     Name  Age Department   Salary         City
1      2    Alice   24         HR  77616.0      Chicago
2      3    David   37         HR  55139.0      Houston
5      6      Bob   50         HR  94535.0      Chicago
7      8  Charlie   49         HR  75856.0     New York
9     10    Alice   50         HR  54230.0      Houston
..   ...      ...  ...        ...      ...          ...
985  986      Bob   30         HR  59098.0  Los Angeles
986  987      Eva   58         HR  54500.0      Chicago
987  988    Alice   24         HR  74102.0     New York
989  990  Charlie   35         HR  54443.0      Houston
992  993  Charlie   58         HR  95749.0  Los Angeles

[182 rows x 6 columns]

In [ ]:
grouped=data.groupby('Department')
print(grouped)#NO output for this groupby
data.groupby('City').mean(numeric_only=True)#It gives avergae value of that column

<pandas.core.groupby.generic.DataFrameGroupBy object at 0x79aea73d7b50>

                     ID        Age        Salary
City
Chicago      516.196653  39.259414  73078.912134
Houston      496.995516  40.049327  72924.217195
Los Angeles  489.728682  39.961240  77481.148438
New York     502.797834  39.707581  73451.829091

In [ ]:
data.groupby('City').sum(numeric_only=True)#add all the values in that column

                 ID    Age      Salary
City
Chicago      123371   9383  17465860.0
Houston      110830   8931  16116252.0
Los Angeles  126350  10310  19835174.0
New York     139275  10999  20199253.0

In [ ]:
df1=data[['ID','Name','Department']]
df2=data[['ID','Salary','City']]
pd.concat(df1.head(2),df1.tail(2))

TypeError: concat() takes 1 positional argument but 2 were given